import { MigrationInterface, QueryRunner } from 'typeorm';

export class initial1623669429933 implements MigrationInterface {
    name = 'initial1623669429933'

    public async up (queryRunner: QueryRunner): Promise<void> {
      await queryRunner.query('CREATE TABLE `channel` (`id` int NOT NULL AUTO_INCREMENT, `holo_api_id` int NOT NULL, `yt_channel_id` varchar(24) NOT NULL, `twitter_link` varchar(64) NOT NULL, `name` varchar(128) NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB');
      await queryRunner.query('CREATE TABLE `channel_nickname` (`nickname` varchar(128) NOT NULL, `channelId` int NULL, PRIMARY KEY (`nickname`)) ENGINE=InnoDB');
      await queryRunner.query('CREATE TABLE `live` (`id` int NOT NULL AUTO_INCREMENT, `yt_video_key` varchar(64) NOT NULL, `title` varchar(256) NOT NULL, `live_status` enum (\'upcoming\', \'live\', \'ended\') NOT NULL DEFAULT \'upcoming\', `pub_status` enum (\'waiting\', \'published\') NOT NULL DEFAULT \'waiting\', `live_schedule` timestamp NULL, `live_start` timestamp NULL, `live_end` timestamp NULL, `channelId` int NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB');
      await queryRunner.query('CREATE TABLE `subscription` (`id` int NOT NULL AUTO_INCREMENT, `discord_channel_id` varchar(20) NOT NULL, `channelId` int NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB');
      await queryRunner.query('ALTER TABLE `channel_nickname` ADD CONSTRAINT `FK_8cfb9d1991021168ca62f05cc48` FOREIGN KEY (`channelId`) REFERENCES `channel`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION');
      await queryRunner.query('ALTER TABLE `live` ADD CONSTRAINT `FK_dba7f923b39a4b30c39b893dfcc` FOREIGN KEY (`channelId`) REFERENCES `channel`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION');
      await queryRunner.query('ALTER TABLE `subscription` ADD CONSTRAINT `FK_d60af4b852e9578102269d83f3d` FOREIGN KEY (`channelId`) REFERENCES `channel`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION');

      // INSERT INTO `channel`
      await queryRunner.query('INSERT INTO `channel` (`id`,`holo_api_id`,`yt_channel_id`,`twitter_link`,`name`) VALUES (1,1,"UCD8HOxPs4Xvsm8H0ZxXGiBw","yozoramel","Mel Channel 夜空メルチャンネル");');
      await queryRunner.query('INSERT INTO `channel` (`id`,`holo_api_id`,`yt_channel_id`,`twitter_link`,`name`) VALUES (2,2,"UCa9Y57gfeY0Zro_noHRVrnw","himemoriluna","Luna Ch. 姫森ルーナ");');
      await queryRunner.query('INSERT INTO `channel` (`id`,`holo_api_id`,`yt_channel_id`,`twitter_link`,`name`) VALUES (3,3,"UCwL7dgTxKo8Y4RFIKWaf8gA","aragamioga","Oga Ch.荒咬オウガ");');
      await queryRunner.query('INSERT INTO `channel` (`id`,`holo_api_id`,`yt_channel_id`,`twitter_link`,`name`) VALUES (4,4,"UChAnqc_AY5_I3Px5dig3X1Q","inugamikorone","Korone Ch. 戌神ころね");');
      await queryRunner.query('INSERT INTO `channel` (`id`,`holo_api_id`,`yt_channel_id`,`twitter_link`,`name`) VALUES (5,5,"UC0TXe_LYZ4scaW2XMyi5_kw","AZKi_VDiVA","AZKi Channel");');
      await queryRunner.query('INSERT INTO `channel` (`id`,`holo_api_id`,`yt_channel_id`,`twitter_link`,`name`) VALUES (6,6,"UC1CfXB_kRs3C-zaeTG3oGyg","akaihaato","Akaihaato Ch. 赤井はあと");');
      await queryRunner.query('INSERT INTO `channel` (`id`,`holo_api_id`,`yt_channel_id`,`twitter_link`,`name`) VALUES (7,7,"UCKeAhJvy8zgXWbh9duVjIaQ","arurandeisu","Aruran Ch. アルランディス");');
      await queryRunner.query('INSERT INTO `channel` (`id`,`holo_api_id`,`yt_channel_id`,`twitter_link`,`name`) VALUES (8,8,"UCsehvfwaWF6nWuFnXI0AqZQ","tsukishitakaoru","Kaoru Ch.月下カオル");');
      await queryRunner.query('INSERT INTO `channel` (`id`,`holo_api_id`,`yt_channel_id`,`twitter_link`,`name`) VALUES (9,9,"UCJFZiqLMntJufDCHc6bQixg","","hololive ホロライブ - VTuber Group");');
      await queryRunner.query('INSERT INTO `channel` (`id`,`holo_api_id`,`yt_channel_id`,`twitter_link`,`name`) VALUES (10,10,"UCXTpFs_3PqI41qX2d9tL2Rw","murasakishionch","Shion Ch. 紫咲シオン");');
      await queryRunner.query('INSERT INTO `channel` (`id`,`holo_api_id`,`yt_channel_id`,`twitter_link`,`name`) VALUES (11,11,"UCp-5t9SrOQwXMU7iIjQfARg","ookamimio","Mio Channel 大神ミオ");');
      await queryRunner.query('INSERT INTO `channel` (`id`,`holo_api_id`,`yt_channel_id`,`twitter_link`,`name`) VALUES (12,12,"UC-hM6YJuNYVAmUWxeIr9FeA","sakuramiko35","Miko Ch. さくらみこ");');
      await queryRunner.query('INSERT INTO `channel` (`id`,`holo_api_id`,`yt_channel_id`,`twitter_link`,`name`) VALUES (13,13,"UCdn5BQ06XqgXoAxIhbqw5Rg","shirakamifubuki","フブキCh。白上フブキ");');
      await queryRunner.query('INSERT INTO `channel` (`id`,`holo_api_id`,`yt_channel_id`,`twitter_link`,`name`) VALUES (14,14,"UCS9uQI-jC3DE0L4IpXyvr6w","kiryucoco","Coco Ch. 桐生ココ");');
      await queryRunner.query('INSERT INTO `channel` (`id`,`holo_api_id`,`yt_channel_id`,`twitter_link`,`name`) VALUES (15,15,"UCHj_mh57PVMXhAUDphUQDFA","","Akai Haato Sub 赤井はあと");');
      await queryRunner.query('INSERT INTO `channel` (`id`,`holo_api_id`,`yt_channel_id`,`twitter_link`,`name`) VALUES (16,16,"UCGNI4MENvnsymYjKiZwv9eg","kishidotemma","Temma Ch. 岸堂天真");');
      await queryRunner.query('INSERT INTO `channel` (`id`,`holo_api_id`,`yt_channel_id`,`twitter_link`,`name`) VALUES (17,17,"UC9mf_ZVpouoILRY9NUIaK-w","rikkaroid","Rikka ch.律可");');
      await queryRunner.query('INSERT INTO `channel` (`id`,`holo_api_id`,`yt_channel_id`,`twitter_link`,`name`) VALUES (18,18,"UCEzsociuFqVwgZuMaZqaCsg","kagamikirach","Kira Ch. 鏡見キラ");');
      await queryRunner.query('INSERT INTO `channel` (`id`,`holo_api_id`,`yt_channel_id`,`twitter_link`,`name`) VALUES (19,19,"UCAoy6rzhSf4ydcYjJw3WoVg","airaniiofifteen","Airani Iofifteen Channel hololive-ID");');
      await queryRunner.query('INSERT INTO `channel` (`id`,`holo_api_id`,`yt_channel_id`,`twitter_link`,`name`) VALUES (20,20,"UCANDOlYTJT7N5jlRC3zfzVA","yukokuroberu","Roberu Ch. 夕刻ロベル");');
      await queryRunner.query('INSERT INTO `channel` (`id`,`holo_api_id`,`yt_channel_id`,`twitter_link`,`name`) VALUES (21,21,"UCLbtM3JZfRTg8v2KGag-RMw","","AkiRose Ch.アキ・ローゼンタールSub");');
      await queryRunner.query('INSERT INTO `channel` (`id`,`holo_api_id`,`yt_channel_id`,`twitter_link`,`name`) VALUES (22,22,"UCP0BspO_AMEe3aQqqpo89Dg","moonahoshinova","Moona Hoshinova hololive-ID");');
      await queryRunner.query('INSERT INTO `channel` (`id`,`holo_api_id`,`yt_channel_id`,`twitter_link`,`name`) VALUES (23,23,"UCvaTdHTWBGv3MKj3KVqJVCw","nekomataokayu","Okayu Ch. 猫又おかゆ");');
      await queryRunner.query('INSERT INTO `channel` (`id`,`holo_api_id`,`yt_channel_id`,`twitter_link`,`name`) VALUES (24,24,"UCQ0UDLQCjY0rmuxCDE38FGg","natsuiromatsuri","Matsuri Channel 夏色まつり");');
      await queryRunner.query('INSERT INTO `channel` (`id`,`holo_api_id`,`yt_channel_id`,`twitter_link`,`name`) VALUES (25,25,"UCqm3BQLlJfvkTsX_hvm0UmA","tsunomakiwatame","Watame Ch. 角巻わため");');
      await queryRunner.query('INSERT INTO `channel` (`id`,`holo_api_id`,`yt_channel_id`,`twitter_link`,`name`) VALUES (26,26,"UCdyqAaZDKHXg4Ahi7VENThQ","shiroganenoel","Noel Ch. 白銀ノエル");');
      await queryRunner.query('INSERT INTO `channel` (`id`,`holo_api_id`,`yt_channel_id`,`twitter_link`,`name`) VALUES (27,27,"UCl_gCybOJRIgOXw6Qb4qJzQ","uruharushia","Rushia Ch. 潤羽るしあ");');
      await queryRunner.query('INSERT INTO `channel` (`id`,`holo_api_id`,`yt_channel_id`,`twitter_link`,`name`) VALUES (28,28,"UC6t3-_N8A6ME1JShZHHqOMw","miyabihanasaki","Miyabi Ch. 花咲みやび");');
      await queryRunner.query('INSERT INTO `channel` (`id`,`holo_api_id`,`yt_channel_id`,`twitter_link`,`name`) VALUES (29,29,"UCZlDXzGoo7d44bwdNObFacg","amanekanatach","Kanata Ch. 天音かなた");');
      await queryRunner.query('INSERT INTO `channel` (`id`,`holo_api_id`,`yt_channel_id`,`twitter_link`,`name`) VALUES (30,30,"UC1opHUrw8rvnsadT-iGp7Cg","minatoaqua","Aqua Ch. 湊あくあ");');
      await queryRunner.query('INSERT INTO `channel` (`id`,`holo_api_id`,`yt_channel_id`,`twitter_link`,`name`) VALUES (31,31,"UCOyYb1c43VlX9rc_lT6NKQw","ayunda_risu","Ayunda Risu Ch. hololive-ID");');
      await queryRunner.query('INSERT INTO `channel` (`id`,`holo_api_id`,`yt_channel_id`,`twitter_link`,`name`) VALUES (32,32,"UCFTLzh12_nrtzqBPsTCqenA","akirosenthal","アキロゼCh。Vtuber/ホロライブ所属");');
      await queryRunner.query('INSERT INTO `channel` (`id`,`holo_api_id`,`yt_channel_id`,`twitter_link`,`name`) VALUES (33,33,"UC7fk0CB07ly8oSl0aqKkqFg","nakiriayame","Nakiri Ayame Ch. 百鬼あやめ");');
      await queryRunner.query('INSERT INTO `channel` (`id`,`holo_api_id`,`yt_channel_id`,`twitter_link`,`name`) VALUES (34,34,"UC1suqwovbL1kzsoaZgFZLKg","yuzukichococh","Choco Ch. 癒月ちょこ");');
      await queryRunner.query('INSERT INTO `channel` (`id`,`holo_api_id`,`yt_channel_id`,`twitter_link`,`name`) VALUES (35,35,"UCp3tgHXw_HI0QMk1K8qh3gQ","","Choco subCh. 癒月ちょこ");');
      await queryRunner.query('INSERT INTO `channel` (`id`,`holo_api_id`,`yt_channel_id`,`twitter_link`,`name`) VALUES (36,36,"UC1DCedRgGHBdm81E1llLhOQ","usadapekora","Pekora Ch. 兎田ぺこら");');
      await queryRunner.query('INSERT INTO `channel` (`id`,`holo_api_id`,`yt_channel_id`,`twitter_link`,`name`) VALUES (37,37,"UCNVEsYbiZjH5QLmGeSgTSzg","astelleda","astel ch.アステル");');
      await queryRunner.query('INSERT INTO `channel` (`id`,`holo_api_id`,`yt_channel_id`,`twitter_link`,`name`) VALUES (38,38,"UCvInZx9h3jC2JzsIzoOebWg","shiranuiflare","Flare Ch. 不知火フレア");');
      await queryRunner.query('INSERT INTO `channel` (`id`,`holo_api_id`,`yt_channel_id`,`twitter_link`,`name`) VALUES (39,39,"UCDqI2jOz0weumE8s7paEk6g","robocosan","Roboco Ch. - ロボ子");');
      await queryRunner.query('INSERT INTO `channel` (`id`,`holo_api_id`,`yt_channel_id`,`twitter_link`,`name`) VALUES (40,40,"UChSvpZYRPh0FvG4SJGSga3g","kageyamashien","Shien Ch.影山シエン");');
      await queryRunner.query('INSERT INTO `channel` (`id`,`holo_api_id`,`yt_channel_id`,`twitter_link`,`name`) VALUES (41,41,"UCp6993wxpyDPHUpavwDFqgg","tokino_sora","SoraCh. ときのそらチャンネル");');
      await queryRunner.query('INSERT INTO `channel` (`id`,`holo_api_id`,`yt_channel_id`,`twitter_link`,`name`) VALUES (42,42,"UCZgOv3YDEs-ZnZWDYVwJdmA","kanadeizuru","Izuru Ch. 奏手イヅル");');
      await queryRunner.query('INSERT INTO `channel` (`id`,`holo_api_id`,`yt_channel_id`,`twitter_link`,`name`) VALUES (43,43,"UCvzGlP9oQwU--Y0r9id_jnA","oozorasubaru","Subaru Ch. 大空スバル");');
      await queryRunner.query('INSERT INTO `channel` (`id`,`holo_api_id`,`yt_channel_id`,`twitter_link`,`name`) VALUES (44,44,"UCCzUftO8KOVkV4wQG1vkUvg","houshoumarine","Marine Ch. 宝鐘マリン");');
      await queryRunner.query('INSERT INTO `channel` (`id`,`holo_api_id`,`yt_channel_id`,`twitter_link`,`name`) VALUES (45,45,"UC1uv2Oq6kNxgATlCiez59hw","tokoyamitowa","Towa Ch. 常闇トワ");');
      await queryRunner.query('INSERT INTO `channel` (`id`,`holo_api_id`,`yt_channel_id`,`twitter_link`,`name`) VALUES (46,46,"UC5CwaMl1eIgY8h02uZw7u8A","suisei_hosimati","Suisei Channel");');
      await queryRunner.query('INSERT INTO `channel` (`id`,`holo_api_id`,`yt_channel_id`,`twitter_link`,`name`) VALUES (31879,31879,"UCFKOVgVbGmX65RxO3EtH3iw","yukihanalamy","Lamy Ch. 雪花ラミィ");');
      await queryRunner.query('INSERT INTO `channel` (`id`,`holo_api_id`,`yt_channel_id`,`twitter_link`,`name`) VALUES (31880,31880,"UCAWSyEs_Io8MtpY3m-zqILA","momosuzunene","Nene Ch.桃鈴ねね");');
      await queryRunner.query('INSERT INTO `channel` (`id`,`holo_api_id`,`yt_channel_id`,`twitter_link`,`name`) VALUES (31881,31881,"UCUKD-uaobj9jiqB-VXt71mA","shishirobotan","Botan Ch.獅白ぼたん");');
      await queryRunner.query('INSERT INTO `channel` (`id`,`holo_api_id`,`yt_channel_id`,`twitter_link`,`name`) VALUES (31882,31882,"UCgZuwn-O7Szh9cAgHqJ6vjw","manoaloe","Aloe Ch.魔乃アロエ");');
      await queryRunner.query('INSERT INTO `channel` (`id`,`holo_api_id`,`yt_channel_id`,`twitter_link`,`name`) VALUES (31883,31883,"UCK9V2B22uJYu3N7eR_BT9QA","omarupolka","Polka Ch. 尾丸ポルカ");');
      await queryRunner.query('INSERT INTO `channel` (`id`,`holo_api_id`,`yt_channel_id`,`twitter_link`,`name`) VALUES (169380,169380,"UCgNVXGlZIFK96XdEY20sVjg","Civia_Hololive","Civia Ch.");');
      await queryRunner.query('INSERT INTO `channel` (`id`,`holo_api_id`,`yt_channel_id`,`twitter_link`,`name`) VALUES (199073,199073,"UCL_qhgtOy0dy1Agp8vkySQg","moricalliope","Mori Calliope Ch. hololive-EN");');
      await queryRunner.query('INSERT INTO `channel` (`id`,`holo_api_id`,`yt_channel_id`,`twitter_link`,`name`) VALUES (199074,199074,"UCHsx4Hqa-1ORjQTh9TYDhww","takanashikiara","Takanashi Kiara Ch. hololive-EN");');
      await queryRunner.query('INSERT INTO `channel` (`id`,`holo_api_id`,`yt_channel_id`,`twitter_link`,`name`) VALUES (199075,199075,"UCMwGHR0BTZuLsmjY_NT5Pwg","ninomaeinanis","Ninomae Ina\'nis Ch. hololive-EN");');
      await queryRunner.query('INSERT INTO `channel` (`id`,`holo_api_id`,`yt_channel_id`,`twitter_link`,`name`) VALUES (199076,199076,"UCoSrY_IQQVpmIRZ9Xf-y93g","gawrgura","Gawr Gura Ch. hololive-EN");');
      await queryRunner.query('INSERT INTO `channel` (`id`,`holo_api_id`,`yt_channel_id`,`twitter_link`,`name`) VALUES (199077,199077,"UCyl1z3jo3XHR1riLFKG5UAg","watsonameliaen","Watson Amelia Ch. hololive-EN");');
      await queryRunner.query('INSERT INTO `channel` (`id`,`holo_api_id`,`yt_channel_id`,`twitter_link`,`name`) VALUES (200275,200275,"UCotXwY6s8pWmuWd_snKYjhg","hololive_En","hololive English");');
      await queryRunner.query('INSERT INTO `channel` (`id`,`holo_api_id`,`yt_channel_id`,`twitter_link`,`name`) VALUES (214950,214950,"UCfrWoRGlawPQDQxxeIDRP0Q","hololive_Id","hololive Indonesia");');
      await queryRunner.query('INSERT INTO `channel` (`id`,`holo_api_id`,`yt_channel_id`,`twitter_link`,`name`) VALUES (214951,214951,"UCWsfcksUUpoEvhia0_ut0bA","holostarstv","holostars ホロスターズ - VTuber Group");');
      await queryRunner.query('INSERT INTO `channel` (`id`,`holo_api_id`,`yt_channel_id`,`twitter_link`,`name`) VALUES (676413,676413,"UCYz_5n-uDuChHtLo7My1HnQ","kureijiollie","Kureiji Ollie Ch. hololive-ID");');
      await queryRunner.query('INSERT INTO `channel` (`id`,`holo_api_id`,`yt_channel_id`,`twitter_link`,`name`) VALUES (676414,676414,"UC727SQYUvx5pDDGQpTICNWg","anyamelfissa","Anya Melfissa Ch. hololive-ID");');
      await queryRunner.query('INSERT INTO `channel` (`id`,`holo_api_id`,`yt_channel_id`,`twitter_link`,`name`) VALUES (676415,676415,"UChgTyjG-pdNvxxhdsXfHQ5Q","pavoliareine","Pavolia Reine Ch. hololive-ID");');

      // INSERT INTO `channel_nickname`
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'mel\', 1);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'yozora\', 1);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'yozoramel\', 1);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'himemori\', 2);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'himemoriluna\', 2);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'luna\', 2);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'aragami\', 3);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'aragamioga\', 3);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'oga\', 3);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'inugami\', 4);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'inugamikorone\', 4);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'korone\', 4);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'AZKi\', 5);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'akai\', 6);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'akaihaato\', 6);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'Haachama\', 6);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'haato\', 6);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'arurandeisu\', 7);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'kaoru\', 8);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'tsukishita\', 8);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'tsukishitakaoru\', 8);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'hololive\', 9);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'murasaki\', 10);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'murasakishionch\', 10);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'shion\', 10);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'mio\', 11);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'ookami\', 11);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'ookamimio\', 11);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'35\', 12);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'miko\', 12);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'sakura\', 12);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'sakuramiko\', 12);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'fubuki\', 13);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'shirakami\', 13);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'shirakamifubuki\', 13);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'coco\', 14);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'kiryu\', 14);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'kiryucoco\', 14);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'kishido\', 16);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'kishidotemma\', 16);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'temma\', 16);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'rikka\', 17);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'rikkaroid\', 17);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'kagami\', 18);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'kagamikira\', 18);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'kira\', 18);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'airani\', 19);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'airaniiofifteen\', 19);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'Iofi\', 19);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'iofifteen\', 19);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'roberu\', 20);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'yukoku\', 20);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'yukokuroberu\', 20);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'hoshinova\', 22);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'moona\', 22);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'moonahoshinova\', 22);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'nekomata\', 23);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'nekomataokayu\', 23);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'okayu\', 23);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'matsuri\', 24);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'natsuiro\', 24);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'natsuiromatsuri\', 24);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'tsunomaki\', 25);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'tsunomakiwatame\', 25);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'watame\', 25);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'noel\', 26);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'shirogane\', 26);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'shiroganenoel\', 26);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'rushia\', 27);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'uruha\', 27);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'uruharushia\', 27);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'hanasaki\', 28);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'hanasakimiyabi\', 28);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'miyabi\', 28);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'miyabihanasaki\', 28);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'amane\', 29);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'amanekanata\', 29);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'kanata\', 29);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'aqua\', 30);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'minato\', 30);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'minatoaqua\', 30);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'ayunda\', 31);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'ayundarisu\', 31);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'risu\', 31);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'Aki\', 32);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'AkiRose\', 32);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'AkiRosenthal\', 32);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'ayame\', 33);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'nakiri\', 33);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'nakiriayame\', 33);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'choco\', 34);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'yuzuki\', 34);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'yuzukichoco\', 34);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'pekora\', 36);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'usada\', 36);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'usadapekora\', 36);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'astel\', 37);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'astelleda\', 37);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'leda\', 37);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'flare\', 38);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'shiranui\', 38);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'shiranuiflare\', 38);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'roboco\', 39);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'robocosan\', 39);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'kageyama\', 40);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'kageyamashien\', 40);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'shien\', 40);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'sora\', 41);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'tokino\', 41);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'tokinosora\', 41);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'izuru\', 42);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'kanade\', 42);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'kanadeizuru\', 42);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'oozora\', 43);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'oozorasubaru\', 43);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'subaru\', 43);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'houshou\', 44);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'houshoumarine\', 44);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'marine\', 44);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'Senchou\', 44);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'tokoyami\', 45);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'tokoyamitowa\', 45);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'towa\', 45);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'Hoshimachi\', 46);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'HoshimachiSuisei\', 46);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'Suisei\', 46);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'lamy\', 31879);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'yukihana\', 31879);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'yukihanalamy\', 31879);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'momosuzu\', 31880);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'momosuzunene\', 31880);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'nene\', 31880);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'botan\', 31881);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'shishiro\', 31881);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'shishirobotan\', 31881);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'aloe\', 31882);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'mano\', 31882);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'manoaloe\', 31882);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'omaru\', 31883);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'omarupolka\', 31883);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'polka\', 31883);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'Civia\', 169380);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'Cali\', 199073);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'Calliope\', 199073);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'Mori\', 199073);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'MoriCalliope\', 199073);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'Kiara\', 199074);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'Takanashi\', 199074);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'TakanashiKiara\', 199074);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'Ina\', 199075);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'Ninomae\', 199075);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'NinomaeInanis\', 199075);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'Gawr\', 199076);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'GawrGura\', 199076);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'Gura\', 199076);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'Ame\', 199077);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'Amelia\', 199077);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'AmeliaWatson\', 199077);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'Watson\', 199077);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'WatsonAmelia\', 199077);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'hololiveEN\', 200275);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'hololiveID\', 214950);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'holostar\', 214951);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'holostars\', 214951);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'Kureiji\', 676413);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'KureijiOllie\', 676413);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'Ollie\', 676413);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'Anya\', 676414);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'AnyaMelfissa\', 676414);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'Melfissa\', 676414);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'Pavolia\', 676415);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'PavoliaReine\', 676415);');
      await queryRunner.query('INSERT INTO `channel_nickname` (`nickname`, `channelId`) VALUES (\'Reine\', 676415);');
    }

    public async down (queryRunner: QueryRunner): Promise<void> {
      await queryRunner.query('ALTER TABLE `subscription` DROP FOREIGN KEY `FK_d60af4b852e9578102269d83f3d`');
      await queryRunner.query('ALTER TABLE `live` DROP FOREIGN KEY `FK_dba7f923b39a4b30c39b893dfcc`');
      await queryRunner.query('ALTER TABLE `channel_nickname` DROP FOREIGN KEY `FK_8cfb9d1991021168ca62f05cc48`');
      await queryRunner.query('DROP TABLE `subscription`');
      await queryRunner.query('DROP TABLE `live`');
      await queryRunner.query('DROP TABLE `channel_nickname`');
      await queryRunner.query('DROP TABLE `channel`');
    }

}
