version: "2"
services:
  server:
    container_name: "server"
    command: npm run dev
    build: ./server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/usr/src/app

  db:
    image: mariadb
    container_name: "db"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    environment:
      MYSQL_USER: "mysql_user"
      MYSQL_PASSWORD: "mysql_password"
      MYSQL_ROOT_PASSWORD: "mysql_password"
      MYSQL_DATABASE: "my-db"
    ports:
      - "3306:3306"