export const enum CommandOptionType {
  SUB_COMMAND = 'SUB_COMMAND',
  SUB_COMMAND_GROUP = 'SUB_COMMAND_GROUP',
  STRING = 'STRING',
  INTEGER = 'INTEGER',
  BOOLEAN = 'BOOLEAN',
  USER = 'USER',
  CHANNEL = 'CHANNEL',
  ROLE = 'ROLE',
  MENTIONABLE = 'MENTIONABLE',
}