# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2

    - run: cp ./server/package-lock.json ./package-lock.json

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - run: npm ci
      working-directory: ./server
    
    - run: npm run lint
      working-directory: ./server
    
    - run: npm run build
      working-directory: ./server
    
    #- run: npm test
    
    - name: Copy Files
      working-directory: ./server
      run: mkdir uploadFiles && cp -r dist uploadFiles/dist && cp package.json uploadFiles/package.json && cp package-lock.json uploadFiles/package-lock.json
      
    
    - name: Upload Files
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: ${{ secrets.FTP_URI }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./server/uploadFiles/
